# Generated by Django 4.2.7 on 2025-07-29 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("question_answering", "Question Answering"),
                            ("text_summarization", "Text Summarization"),
                            ("creative_generation", "Creative Generation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("factual", "Factual & Direct"),
                            ("analytical", "Analytical & Detailed"),
                            ("educational", "Educational & Teaching"),
                            ("concise", "Concise Paragraph"),
                            ("bullet_points", "Bullet Points"),
                            ("executive", "Executive Summary"),
                            ("storytelling", "Creative Storytelling"),
                            ("professional", "Professional Content"),
                            ("innovative", "Innovative & Unique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function_type", models.CharField(max_length=50)),
                ("query", models.TextField()),
                ("response", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("suggestions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "query_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="api.queryhistory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("function_type", models.CharField(max_length=50)),
                ("total_queries", models.IntegerField(default=0)),
                ("avg_processing_time", models.FloatField(default=0.0)),
                ("avg_rating", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "function_type")},
            },
        ),
    ]
